name: UI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [ chromium, firefox ]

    steps:
      # 1. Клонируем репозиторий
      - name: Check out repository
        uses: actions/checkout@v5

      # 2. Установка Python
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      # 3. Установка зависимостей и браузеров Playwright
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      # 4. Установка Allure CLI (исправлено)
      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.32.2/allure-2.32.2.tgz
          tar -zxvf allure-2.32.2.tgz
          sudo mv allure-2.32.2 /opt/allure
          # Добавляем в PATH для следующих шагов
          echo "/opt/allure/bin" >> $GITHUB_PATH
          # Сразу проверяем установку используя полный путь
          /opt/allure/bin/allure --version

      # 5. Запуск тестов с выбранным браузером
      - name: Run Playwright tests with pytest
        run: |
          pytest --browser=${{ matrix.browser }} --alluredir=allure-results -m regression -v

      # 6. Сохраняем результаты Allure как артефакт
      - name: Upload Allure results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: allure-results
          if-no-files-found: warn